ci: fail workflow when Cacti log contains FATAL/ERROR/WARNING entries (#35)

diff --git a/.github/workflows/plugin-ci-workflow.yml b/.github/workflows/plugin-ci-workflow.yml
--- a/.github/workflows/plugin-ci-workflow.yml
+++ b/.github/workflows/plugin-ci-workflow.yml
@@ -1,9 +1,9 @@
 # +-------------------------------------------------------------------------+
 # | Copyright (C) 2004-2026 The Cacti Group                                 |
 # |                                                                         |
-# | This program is free software; you can redistribute it and/or          |
+# | This program is free software; you can redistribute it and/or           |
 # | modify it under the terms of the GNU General Public License             |
-# | as published by the Free Software Foundation; either version 2         |
+# | as published by the Free Software Foundation; either version 2          |
 # | of the License, or (at your option) any later version.                  |
 # |                                                                         |
 # | This program is distributed in the hope that it will be useful,         |
@@ -263,4 +263,14 @@ jobs:
         if [ -f ${{ github.workspace }}/cacti/log/cacti.log ]; then
           echo "=== Cacti Log ==="
           sudo cat ${{ github.workspace }}/cacti/log/cacti.log
+        fi
+
+    - name: Check Cacti Logs for Errors
+      if: always()
+      run: |
+        if [ -f ${{ github.workspace }}/cacti/log/cacti.log ]; then
+          if grep -E "FATAL:|ERROR:|WARNING:" ${{ github.workspace }}/cacti/log/cacti.log; then
+            echo "Found FATAL/ERROR/WARNING entries in Cacti log"
+            exit 1
+          fi
         fi
